version: '3.5'

services: 
  php:
    image: php:7.2-cli
    build: '.'
    ports:
      - 3000:80
    command: php /usr/local/src/artisan serve --host 0.0.0.0 --port=80
    volumes:
      - composer_home:/tmp
      - ./demo:/usr/local/src
    environment:
      COMPOSER_HOME: /tmp
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  node:
    image: node
    command: bash -c "yarn && yarn watch"
    volumes:
      - ./demo:/usr/local/src
      - ./demo/node_modules:/usr/local/src/node_modules
    working_dir: /usr/local/src

  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80

volumes:
  composer_home:
