/**
 * Fetch users
 */
export const FETCH_USERS_REQUEST = `FETCH_USERS_REQUEST`;
export const FETCH_USERS_SUCCESS = `FETCH_USERS_SUCCESS`;
export const FETCH_USERS_FAILURE = `FETCH_USERS_FAILURE`;

/**
 * Fetch user data
 */
export const FETCH_USER_DATA_REQUEST = `FETCH_USER_DATA_REQUEST`;
export const FETCH_USER_DATA_SUCCESS = `FETCH_USER_DATA_SUCCESS`;
export const FETCH_USER_DATA_FAILURE = `FETCH_USER_DATA_FAILURE`;
